// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_practice/test/features/product/controllers/product_list_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_practice/features/product/infra/product_repository.dart'
    as _i3;
import 'package:flutter_practice/features/product/models/product.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProduct_0 extends _i1.SmartFake implements _i2.Product {
  _FakeProduct_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  @override
  _i4.Future<List<_i2.Product>> fetchProducts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, []),
            returnValue: _i4.Future<List<_i2.Product>>.value(<_i2.Product>[]),
            returnValueForMissingStub: _i4.Future<List<_i2.Product>>.value(
              <_i2.Product>[],
            ),
          )
          as _i4.Future<List<_i2.Product>>);

  @override
  _i4.Future<_i2.Product> fetchProductDetail(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductDetail, [id]),
            returnValue: _i4.Future<_i2.Product>.value(
              _FakeProduct_0(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Product>.value(
              _FakeProduct_0(
                this,
                Invocation.method(#fetchProductDetail, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Product>);

  @override
  _i4.Future<void> addProduct(_i2.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
